openapi: '3.0.2'
info:
  title: سامانه کانبان
  version: '0.0.1'
  description: سامانه ای برای مدیریت و نظارت بر روند پیشرفت کارها
servers:
  - url: /api/v1
tags:
  - name: users
    description: سرویس های مرتبط با کاربران
  - name: kanbans
    description: سرویس های مرتبط با کانبان
  - name: commonServices
    description: سرویس های مشترک
  - name: entities
    description: سرویس های مرتبط با هستارها
  - name: cards
    description: سرویس های مرتبط با کارتها
  - name: queues
    description: سرویس های مرتبط با صف ها
  - name: labels
    description: سرویس های مرتبط با برچسب ها
paths:
  # users
  /users:
    $ref: './resources/users/users.yaml'
  /users/login:
    $ref: './resources/users/login.yaml'
  /users/change-password:
    $ref: './resources/users/change-password.yaml'
  # kanbans
  /kanbans:
    $ref: './resources/kanbans/kanbans.yaml'
  /kanban:
    $ref: './resources/kanbans/kanban.yaml'
  /kanban/{id}:
    $ref: './resources/kanbans/deleteAndGetKanban.yaml'
  /kanban/{id}/queues:
    $ref: './resources/kanbans/getKanbanQueues.yaml'
  /kanban/{id}/users:
    $ref: './resources/kanbans/getKanbanUsers.yaml'
  /kanban/{id}/labels:
    $ref: './resources/kanbans/getKanbanLabels.yaml'
  # commonServices
  /users/{name}:
    $ref: './resources/users/findUsersByName.yaml'
  /accessibilities/{name}:
    $ref: './resources/accessibilities/findAccessibilityByName.yaml'
  /logs:
    $ref: './resources/common/logs.yaml'
  # entities
  /entities:
    $ref: './resources/entities/getEntities.yaml'
  /entity:
    $ref: './resources/entities/entity.yaml'
  /entity/{id}:
    $ref: './resources/entities/deleteAndGetEntity.yaml'
  #cards
  /card/changeCardPriority:
    $ref: './resources/cards/changeCardPriority.yaml'
  /card/archiveCard:
    $ref: './resources/cards/archiveCard.yaml'
  /card/changeCardQueue:
    $ref: './resources/cards/changeCardQueue.yaml'
  /card:
    $ref: './resources/cards/card.yaml'
  /card/{id}:
    $ref: './resources/cards/deleteAndGetCard.yaml'
  /cards:
    $ref: './resources/cards/getCards.yaml'
  #queues
  /queue:
    $ref: './resources/queues/queue.yaml'
  /queue/{id}:
    $ref: './resources/queues/deleteAndGetQueue.yaml'
  /queue/changeQueuePriority:
    $ref: './resources/queues/changeQueuePriority.yaml'
  #labels
  /label:
    $ref: './resources/labels/label.yaml'
  /label/{id}:
    $ref: './resources/labels/deleteLabel.yaml'