openapi: '3.0.2'
info:
  title: سامانه کانبان
  version: '0.0.1'
  description: سامانه ای برای مدیریت و نظارت بر روند پیشرفت کارها
servers:
  - url: /api/v1
tags:
  - name: users
    description: سرویس های مرتبط با کاربران
  - name: kanbans
    description: سرویس های مرتبط با کانبان
  - name: commonServices
    description: سرویس های مشترک
  - name: entities
    description: سرویس های مرتبط با هستارها
  - name: cards
    description: سرویس های مرتبط با کارتها
  - name: queues
    description: سرویس های مرتبط با صف ها
paths:
  # users
  /users:
    $ref: './resources/users/users.yaml'
  /users/login:
    $ref: './resources/users/login.yaml'
  /users/change-password:
    $ref: './resources/users/change-password.yaml'
  # kanbans
  /kanbans/getKanbans:
    $ref: './resources/kanbans/getKanbans.yaml'
  /kanbans/deleteKanban:
    $ref: './resources/kanbans/deleteKanban.yaml'
  /kanbans/getKanban:
    $ref: './resources/kanbans/getKanban.yaml'
  /kanbans/addKanban:
    $ref: './resources/kanbans/addKanban.yaml'
  /kanbans/editKanban:
    $ref: './resources/kanbans/editKanban.yaml'
  /kanbans/getKanbanQueues:
    $ref: './resources/kanbans/getKanbanQueues.yaml'
  # commonServices
  /findUsersByName:
    $ref: './resources/users/findUsersByName.yaml'
  /findGroupsByName:
    $ref: './resources/groups/findGroupsByName.yaml'
  # entities
  /entites/findEntities:
    $ref: './resources/entities/findEntities.yaml'
  #cards
  /cards/changeCardPriority:
    $ref: './resources/cards/changeCardPriority.yaml'
  /cards/deleteCard:
    $ref: './resources/cards/deleteCard.yaml'
  /cards/archiveCard:
    $ref: './resources/cards/archiveCard.yaml'
  /cards/changeCardQueue:
    $ref: './resources/cards/changeCardQueue.yaml'
  /cards/getCard:
    $ref: './resources/cards/getCard.yaml'
  #queues
  /queues/deleteQueue:
    $ref: './resources/queues/deleteQueue.yaml'
  /queues/changeQueuePriority:
    $ref: './resources/queues/changeQueuePriority.yaml'
  /queues/getQueue:
    $ref: './resources/queues/getQueue.yaml'
  /queues/editQueue:
    $ref: './resources/queues/editQueue.yaml'
  /queues/addQueue:
    $ref: './resources/queues/addQueue.yaml'